apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pennypilot
resources:
  - namespace.yaml
  - postgres.yaml
  - app.yaml
  - ingress.yaml
images:
  - name: ghcr.io/OWNER/pennypilot
    newTag: latest
