image:
  repository: ghcr.io/gregarendse/pennypilot-backend
  tag: latest

keel:
  policy: force
  trigger: poll
  pollSchedule: "@midnight"
  approvals: "0"

environment:
  - name: HTTP_ADDR
    value: ":8080"
  - name: DATABASE_URL
    value: "postgres://pennypilot:pennypilot@pennypilot-db:5432/pennypilot?sslmode=disable"
  - name: FRONTEND_URL
    value: "https://pennypilot.arendse.nom.za"

service:
  type: ClusterIP

ports:
  http:
    target: 8080
    protocol: TCP

ingress:
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: pennypilot-api.arendse.nom.za
      path: /
      tls: true
      service:
        name: http

secrets:
  environment:
    - pennypilot-backend-secrets
